### ISSUE TITLE
Верстка хедера: разметка

### ISSUE THREAD

**Issue by Anastacia-Tesli** [Anastacia-Tesli/yandex_landing#11]
Задуман хедер с фиксированным позиционированием (двигается вслед за пользователем)

**Comment by elrouss** [comment]
Не забыть реализовать якорные ссылки с плавным переходом к блокам

**Comment by Anastacia-Tesli** [comment]
Обрати внимание, что в мобильной версии у них может появиться бургерное меню

**Comment by elrouss** [comment]
Учитываю, с CodePen можно будет взять какую-нибудь интересную анимацию
